version: '3.1'
services:
  bot:
    build: .
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: master
    # volumes:
      # - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432